# Generado por script
network:
    version: 2
    ethernets:
        enp6s18:
            nameservers:
                address:
                    - 172.16.50.2
                search: []
    vlans:
        vlan2:
            link: enp6s18
            addresses: [172.16.50.3/23]
            routes:
                - to: 0.0.0.0/0
                via: 172.16.50.2
            nameservers:
                address:
                    -8.8.8.8
